spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:usersdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  cloud:
    config:
      enabled: false

server:
  port: 8081